services:
  postgres:
    image: postgres:latest
    container_name: dm_server
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dm_db
      POSTGRES_USER: dm_admin    # default admin user
      POSTGRES_PASSWORD: dm_admin_pass    # default admin password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  rabbitmq:
    image: rabbitmq:latest
    container_name: dm_queue
    restart: always
    ports:
      - "5672:5672"    # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: dm_user
      RABBITMQ_DEFAULT_PASS: dm_pass

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"

  spring:
    build: ./Paperless/REST/rest
    container_name: dm_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dm_db
      SPRING_DATASOURCE_USERNAME: dm_admin
      SPRING_DATASOURCE_PASSWORD: dm_admin_pass
      SPRING_RABBITMQ_HOST: dm_queue
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: dm_user
      SPRING_RABBITMQ_PASSWORD: dm_pass
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    depends_on:
      - postgres
      - rabbitmq
      - minio
  ocr:
    build: ./Paperless/Services/OcrService
    container_name: dm_ocr
    restart: always
    environment:
      SPRING_RABBITMQ_HOST: dm_queue
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: dm_user
      SPRING_RABBITMQ_PASSWORD: dm_pass

      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

    depends_on:
    - rabbitmq

  web:
    build: ./webui
    container_name: dm_web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - spring
volumes:
  postgres_data:
